volume -= 0.33;
if (image_index == 3) image_index = 0;
else image_index++;
if (volume == 0.34) volume = 0.33;
else if (volume == -0.33) volume = 1;
audio_sound_gain(soundMusic1, volume, 0);
audio_sound_gain(soundMusic2, volume, 0);
audio_sound_gain(soundMusic3, volume, 0);
audio_sound_gain(soundMusic4, volume, 0);
audio_sound_gain(soundMusic5, volume, 0);
audio_sound_gain(soundMusic6, volume, 0);
audio_sound_gain(soundMusic7, volume, 0);
audio_sound_gain(soundMusicTitle, volume, 0);
audio_sound_gain(soundGameOver, 0.8*volume, 0);
audio_sound_gain(soundShoot, 0.5*volume, 0);
audio_sound_gain(soundPUApp, volume, 0);
audio_sound_gain(soundPUPick, volume, 0);
audio_sound_gain(soundDie, 0.6*volume, 0);
audio_sound_gain(soundGem, 0.6*volume, 0);
audio_sound_gain(soundBlip, 0.15*volume, 0);
audio_sound_gain(soundSelect, 0.8*volume, 0);
audio_sound_gain(soundHurt, 0.6*volume, 0);